### PR TITLE
Fix bug in the calculation of synthetic element names.

### LINKED ISSUE #225: [BUG] validation fails if model contains other node types
We are using sds-sdk version 2.0.4 and validation using io.openmanufacturing.sds.aspectmodel.validation.services.AspectModelValidator fails if the model contains other nodes with edges to Aspect Model Element nodes.
We are suspecting this might be the code issue :
Module [sds-aspect-meta-model-java](https://github.com/OpenManufacturingPlatform/sds-sdk/tree/main/core/sds-aspect-meta-model-java)  [io.openmanufacturing.sds.metamodel.loader.MetaModelBaseAttributes](https://github.com/OpenManufacturingPlatform/sds-sdk/blob/main/core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/MetaModelBaseAttributes.java)
```
private static String getSyntheticName( final Resource modelElement, final Model model, final BAMM bamm ) {
      Resource parentModelElement = model.listStatements( null, null, modelElement ).next().getSubject();
      while ( parentModelElement.isAnon() ) {
         parentModelElement = model.listStatements( null, null, parentModelElement ).next().getSubject();
      }      
      ....
```      
If an Aspect Model Element node has 2 edges pointing to it, sometimes the code takes the the wrong edge and in our case second call fails as there is no upper edge.

### PR DESCRIPTION
**Pull request by RaMisess**
Fixes #225

### CODE REVIEW

File: core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/MetaModelBaseAttributes.java [hunk 1]
```diff
@@ -219,6 +219,31 @@ private static String getSyntheticName( final Resource modelElement, final Model
...
+   // We have to be careful when searching for the parent nodes with a regular name - the "listStatements" API returns the matching nodes
+   // in no particular order; with some very specific models this could lead to non-deterministic behavior.
+   // In the following very simplified example we are looking for ":NumberList" as the parent of "_:blankNode", but could get the anonymous node [] instead.
+   // [
+   //  aux:contains _:blankNode ;
+   // ] .
+   // :NumberList a bamm-c:List ;
+   //    bamm-c:elementCharacteristic _:blankNode .
+   // _:blankNode a bamm-c:Trait ;
+   private static Resource getNamedParent( final Resource modelElement, final Model model ) {
```
Comment (atextor) [inline core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/MetaModelBaseAttributes.java:231]: Please add unit test(s) that verify the correct behaviour.

**Review by atextor — CHANGES_REQUESTED** [review]

File: core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/MetaModelBaseAttributes.java (hunk 1 above)
Comment (RaMisess) [reply core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/MetaModelBaseAttributes.java:231]: Done

**Review by atextor — APPROVED** [review]
